examples/demo.py
examples/qt_app.py
examples/qt_app_asyncio.py
examples/wx_app.py
rendercanvas/_loop.py
rendercanvas/base.py
rendercanvas/glfw.py
rendercanvas/jupyter.py
rendercanvas/offscreen.py
rendercanvas/qt.py
rendercanvas/wx.py
tests/test_scheduling.py

Some notes on decisions I came to. I feel like the text below makes little sense for anyone else, since its all a bit hard to explain and the problems are rather subtle. Nevertheless, I think its good to have this on record.
The initialization order is tricky. Taking qt as an example, the mro is:
* QObject
* ...
* QWidget
* BaseRenderCanvas
* QRenderWidget
All is good, except for one thing: I want `BaseRenderCanvas` to set the size and title (and maybe more in the future), because I don't want every subclass to have to bother with that. However, that must happen *after* the  QRenderWidget did its initialization. I played with some ideas, and implemented one where the the backend class (QRenderWidget) must implement `_rc_init` instead of `__init__`. But this is too weird. Thought of …

Refactor initialization and re-order methods

---

docs/backends.rst
docs/conf.py
rendercanvas/auto.py
tests/test_offscreen.py
tests/testutils.py

Implement env vars

---

rendercanvas/asyncio.py

It raises a deprecationwarning since py312, and will be removed in some later version.
I'd expect that `set_event_loop()` will be removed with it, we'll see.

Remove deprecated get_event_loop

---

rendercanvas/asyncio.py

When `loop.run()` was not called, but the canvas is still running, e.g. because in an interactive env, then when the canvas was closed, the interactive loop was stopped. This prevents that.

Dont stop asyncio loop when interactive

---

rendercanvas/_loop.py
rendercanvas/asyncio.py
rendercanvas/base.py
rendercanvas/glfw.py
rendercanvas/qt.py
rendercanvas/wx.py
tests/test_loop.py

See https://github.com/pygfx/pygfx/issues/377
Inspired mostly by https://github.com/encode/uvicorn/blob/master/uvicorn/server.py
Sending sigint will stop the event loop, if we're the one running it. These changes improve the behavior of the base loop implementation, so that the subclasses can actually be made quite a bit simpler.

Handle ctrl-c

---

examples/demo.py
examples/offsceen_threaded.py
rendercanvas/_loop.py
rendercanvas/base.py
rendercanvas/glfw.py
rendercanvas/jupyter.py
rendercanvas/offscreen.py
rendercanvas/qt.py
rendercanvas/stub.py
rendercanvas/wx.py
tests/test_glfw.py
tests/test_scheduling.py

All public methods on canvas are verbs, except `canvas.is_closed()`. The name looks like its a property, but its a method. It does not help that we have `timer.is_running` and `timer.is_one_shot` properties.
This PR renames it to `get_closed()`, the old method is still supported, but with a warning.

Rename is_closed() to get_closed()

---

docs/backends.rst
examples/cube_qt.py
examples/events.py
rendercanvas/auto.py
rendercanvas/glfw.py
rendercanvas/jupyter.py
rendercanvas/offscreen.py
rendercanvas/qt.py
rendercanvas/stub.py
rendercanvas/wx.py
tests/test_backends.py

Use `loop.run()`  instead. I left it for backwards compat, but with loops being able to drive canvases of different backends, this just add confusion.

Remove run function

---

README.md
docs/start.rst
docs/utils.rst
docs/utils_asyncs.rst
docs/utils_bitmappresentadapter.rst
docs/utils_bitmaprenderingcontext.rst
docs/utils_cube.rst
rendercanvas/_events.py
rendercanvas/_loop.py
rendercanvas/utils/asyncadapter.py
rendercanvas/utils/asyncs.py

A bit more docs on async

---

examples/noise.py
rendercanvas/utils/bitmappresentadapter.py

For some reason the bitmap example stopped working for me. Not sure why, but is better practice to use the preferred format anyway.

Fix rendering via bitmap adapter

---

rendercanvas/jupyter.py

The initial logical size for `JupyterRenderCanvas` is (0, 0) by default which causes sporadic divide by zero errors with WGPU validation and also creates issues for CI since `get_frame()` returns blank screenshots and then improperly sized screenshots before returning correct screenshots (I'm guessing until it processes events to resize the canvas?). This changes it so that if a size is specified for the canvas in the constructor, then that size is used for the logical_size in addition to the css width and height. Not sure if we should just change the default size in the constructor from (0, 0) as well.

fix set logical size in `JupyterRenderCanvas`

---

docs/backends.rst
rendercanvas/qt.py
rendercanvas/wx.py

Ref #55
Even calling `winId()` causes issues for Qt widgets. So let's not do it unless we need that id.

Dont get winId in qt and wx with bitmap present-method

---

rendercanvas/qt.py
rendercanvas/wx.py

Thank you for the ability to use bitmap without calling `winId()` @almarklein, I think it might be working well for me just "as is". 👍 
this PR suppresses the `rendercanvas:Qt falling back to offscreen rendering, which is less performant` warning when bitmap was explicitly selected (not really a fallback at that rate)
*edit*:
> I think it might be working well for me just "as is"
maybe not actually, I am seeing a noticeable difference.  will continue to tinker

hide bitmap warning when explicitly picked

---

rendercanvas/base.py

When the context returns a failure message, the exception handling logic tries to "get" a field from the message string instead of the result dict, causing the error not to be displayed correctly:
`AttributeError: 'str' object has no attribute 'get'`

Fix AttributeError on present() "fail" case

---

rendercanvas/glfw.py

GLFW window start at correct size and draw during resize

---

rendercanvas/_context.py
rendercanvas/_events.py
rendercanvas/_loop.py
rendercanvas/base.py
rendercanvas/glfw.py
tests/test_loop.py

Ref https://github.com/pygfx/pygfx/issues/642
* The draw function.
* The canvas context.
* The event handlers (sanity check; likely already happened).

Better canvas cleanup, avoids segfaults on some systems with glfw+wgpu

---

rendercanvas/offscreen.py
rendercanvas/utils/cube.py

Depends on https://github.com/pygfx/wgpu-py/pull/701

Improve HDR support

---

rendercanvas/jupyter.py

Prevent jupyter backend from submitting events that rendercanvas does not (yet) know

---

docs/api.rst
examples/demo.py
rendercanvas/__init__.py
rendercanvas/base.py
rendercanvas/glfw.py
rendercanvas/jupyter.py
rendercanvas/offscreen.py
rendercanvas/qt.py
rendercanvas/stub.py
rendercanvas/wx.py

Closes #27 
The set of supported cursors shape is limited to 10 cursors, that are supported and consistent in all backends. It looks like glfw is the most limiting here.
I think all backends also support custom cursors via a bitmap, but that's out of scope for this PR.

Add canvas.set_cursor()

---

rendercanvas/_events.py
rendercanvas/glfw.py
rendercanvas/qt.py
rendercanvas/wx.py

Closes #78
* glfw
* qt
* wx
(for jupyter it already works via jupyter_rfb since https://github.com/vispy/jupyter_rfb/pull/116)
*I made sure the below behavior is implemented in all backends.*
* Send enter / leave event when the mouse enters / leaves the window.
* The canvas does not emit pointer move events when the pointer has left the canvas, unless a button is pressed (i.e. dragging / mouse tracking).
* When the application loses focus, a leave event is emitted.
* When the application regains focus, an enter event is emitted if the pointer if over the canvas. 
* If the application regained focus by clicking on the canvas, that click does not result in pointer events (down, nor move, nor up).
* When the application does not have focus, it does not emit pointer move events.
Exceptions:
* …

Add pointer_enter and pointer_leave events

---

docs/api.rst
rendercanvas/__init__.py
rendercanvas/_scheduler.py
rendercanvas/base.py

This allows setting the `update_mode` and `max_fps` at runtime. Ref #79 
The default `min_fps` was changed from 1 to 0, so that with update-mode 'ondemand' there really are no draws except from resizes.

Add canvas.set_update_mode()

---

rendercanvas/_scheduler.py
rendercanvas/_version.py

In `wgpu.gui`, one could set `max_fps=-1` to disable the fps cap. Several examples in pygfx do this. In rendercanvas this results in a cap of 1 fps. To avoid frustration about "why the visualization is so slow", let's forbid negative fps caps.

Disallow max_fps=-1

---

rendercanvas/base.py

In https://github.com/pygfx/pygfx/pull/1174 I did some research to how the screen and system settings affect the pixel ratio of the canvas. Let's document the main findings!

Add some docs on pixel ratio
